# this is the MAIN file thing that you run. it uses the other things to do the thing

---
- name: Deploy website locally
  hosts: localhost
  become: true
  roles:
    - webserver
    - webapp

  post_tasks:
    - name: Test endpoint
      ansible.builtin.uri:
        url: http://localhost:80
        status_code: 200
...