# this is the MAIN file thing that you run. it calls roles and other things to do the thing

---
- name: Play 1 - Prepare environment
  hosts: localhost
  connection: local
  become: false

  pre_tasks:
    - name: Ensure Podman is installed
      ansible.builtin.package:
        name: podman
        state: present
      become: true

    - name: Ensure target container is running
      containers.podman.podman_container:
        name: ansible-target
        image: quay.io/fedora/fedora:42
        state: started
        ports:
          - "8080:80"

    - name: Add the running container to inventory for the next play
      ansible.builtin.add_host:
        name: live_container
        ansible_host: ansible-target
        ansible_connection: podman
        ansible_user: root
        ansible_remote_tmp: /tmp

- name: Play 2 - Deploy website inside container
  hosts: live_container
  become: true # sudo

  roles:
    - webserver
    - webapp

  post_tasks:
    - name: Test endpoint
      ansible.builtin.uri:
        url: http://localhost:80
        status_code: 200
...
