# this thing just basically finds it and runs it with some permissions set in case things go wrong
---

- name: Deploy web app from template
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0644'
  
...