# this makes sure the webserver is installed no matter the targeted server
---
- name: Update apt cache (Debian)
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install httpd package (RedHat)
  ansible.builtin.dnf:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
  notify: Restart apache

- name: Install apache2 package (Debian)
  ansible.builtin.apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: restart apache

- name: Ensure service is running
  ansible.builtin.service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: started
    enabled: true
...
